language: java
jdk:
  - openjdk6
  - oraclejdk7
  - oraclejdk8
script: ./travis.sh
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - olamy@apache.org
