language: java
jdk:
  - oraclejdk8
  - jdk9-ea

script: "mvn --show-version --errors --batch-mode -Prun-its clean verify"

cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - olamy@apache.org
